
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - node
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.node.role.controller.io
  resources:
  - noderolecontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operators.node.role.controller.io
  resources:
  - noderolecontrollers/status
  verbs:
  - get
  - patch
  - update
